CRUD/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
]

CRUD/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', view=views.post_list, name='list'),
    path('<int:post_id>', view=views.post_detail, name='detail'),
    path('create/', view=views.create_post, name='create'),
    path('<int:pk>/update/', view=views.update_post, name='update'),
    path('<int:pk>/delete/', view=views.delete_post, name='delete')
]

CRUD/posts/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(verbose_name='제목', max_length=100)
    writer = models.CharField(verbose_name='글쓴이', max_length=50)
    content = models.TextField(verbose_name='내용')
    # DB에는 없는 ORM이라고 함(생성과 업데이트 시각 기록)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # string으로 title 반환
    def __str__(self):
        return self.title

CRUD/posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

CRUD/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from .forms import PostForm


def post_list(request):
    # return HttpResponse('글 리스트')
    '''
    Read(R)
    포스트들을 불러와서 리스트 형태로 보여준다
    '''
    posts = Post.objects.all()
    ctx = {'posts': posts}  # dictionary

    return render(request, template_name='posts/list.html', context=ctx)


def post_detail(request, post_id):
    '''
    Read(R)
    특정 포스트를 불러와서 상세정보를 보여준다
    '''
    post = Post.objects.get(id=post_id)
    ctx = {'post': post}

    return render(request, 'posts/detail.html', context=ctx)


def create_post(request):
    '''
    Create(C)
    포스트를 새로 생성한다
    request method ==> GET(url 입력), POST(저장하기)
    '''
    if request.method == 'POST':
        # 글쓰기 칸을 '저장하기' 눌렀을 때
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('posts:list')
    else:
        # 글쓰기 칸을 보여줄 때
        form = PostForm()
        ctx = {'form': form}

        return render(request, template_name='posts/post_form.html', context=ctx)


def update_post(request, pk):
    '''
    Update(U)
    포스트를 수정하는 뷰
    '''
    # Post.objects.get(id=pk)
    post = get_object_or_404(Post, id=pk)   # error handling

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save()

            return redirect('posts:detail', pk)
    else:
        form = PostForm(instance=post)
        ctx = {'form': form}
        return render(request, 'posts/post_form.html', ctx)


def delete_post(request, pk):
    '''
    Delete(D)
    포스트를 삭제하는 뷰
    '''
    post = get_object_or_404(Post, pk=pk)

    if request.method == "GET":
        return redirect('posts:detail', post.id)
    elif request.method == "POST":
        post.delete()
        return redirect('posts:list')

CRUD/posts/templates/posts/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>포스트 상세정보</title>
</head>
<body>
    <h1>{{post.title}}</h1>
    <span>{{post.writer}}</span> <br>
    <p>{{post.content}}</p>
    <p>{{post.created_at}}</p>
    <p>{{post.updated_at}}</p>
    <a href="{% url 'posts:list' %}">리스트로 돌아가기</a> <br>
    <a href="{% url 'posts:update' post.id %}">수정하기</a> <br>
    <form action="{% url 'posts:delete' post.id %}" method="POST">
        {% csrf_token %}
        <input type="submit" value='삭제하기'>
    </form>
</body>
</html>

CRUD/posts/templates/posts/list.html
<!DOCTYPE html>
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>글 리스트</title>
</head>

<body>
    <a href="{% url 'posts:create' %}">글 생성하기</a>
    {% for post in posts %}
    <h2>제목: <a href="{% url 'posts:detail' post.id %}">{{post.title}}</a></h2> <br>
    <h4>글쓴이: {{post.writer}}</h4> <br>
    ===================================================== <br>
    {% endfor %}
</body>

</html>

CRUD/posts/templates/posts/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>포스트 작성</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>

        <input type="submit" value="저장하기">
    </form>
</body>
</html>